config {
  name: 'Sync from base tables of HAPI DBs (Converted FHIR)',
}

CALL
  `${dataform.projectConfig.defaultDatabase}.hapi_fhir_kobo_converted_data_PROD_public.merge_to_partitioned_table_where_last_updated_after_x_y_ago`(
    ${constants.paramTimestampSubIntervalIntegerValue} +
      TIMESTAMP_DIFF(
        CURRENT_TIMESTAMP,
        TIMESTAMP('${constants.startTimestamp}'),
        MINUTE
      )
      + 1,
    '${constants.paramTimestampSubIntervalDatePartValue}'
  );
